/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_lab4inf_wrb_Integrator */

#ifndef _Included_de_lab4inf_wrb_Integrator
#define _Included_de_lab4inf_wrb_Integrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_lab4inf_wrb_Integrator
 * Method:    integrate
 * Signature: (Lde/lab4inf/wrb/Function;DDD)D
 */
JNIEXPORT jdouble JNICALL Java_de_lab4inf_wrb_Integrator_integrate
  (JNIEnv *, jobject, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
