/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_lab4inf_wrb_Differentiator */

#ifndef _Included_de_lab4inf_wrb_Differentiator
#define _Included_de_lab4inf_wrb_Differentiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_lab4inf_wrb_Differentiator
 * Method:    differentiate
 * Signature: (Lde/lab4inf/wrb/Function;DD)D
 */
JNIEXPORT jdouble JNICALL Java_de_lab4inf_wrb_Differentiator_differentiate
  (JNIEnv *, jobject, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
